### ISSUE TITLE
Mark as public Github Container Registry

### ISSUE THREAD

**Issue by sters** [cloudspannerecosystem/wrench#116]
## WHAT
I introduced publishing container image to GHCR in this PR: https://github.com/cloudspannerecosystem/wrench/pull/111

And the result seems fine. Github actions said it's published.
https://github.com/cloudspannerecosystem/wrench/actions/runs/10213036102/job/28257623430

But the image of `ghcr.io/cloudspannerecosystem/wrench` is still 404.
I think it's marked as private so please change it to public.

## WHY
I wanted to use wrench from the official docker image.

related: https://github.com/cloudspannerecosystem/wrench/issues/82

**Comment by zoncoen** [comment]
Thank you for your feedback. I tried to make it public, but it requires the org admin permission.
I'll contact to admin. 🙏

**Comment by yfuruyama** [comment]
@skuruppu Hi Shanika, I was asked to make this change, but I noticed that I'm no longer the owner of this organization. Could you make this repo's container registry public?

Probably we can change it from here: https://github.com/cloudspannerecosystem/wrench/pkgs/container/wrench

**Comment by skuruppu** [comment]
Sorry for the delay. The package is public now public.

**Comment by yfuruyama** [comment]
Thank you @skuruppu !

**Comment by zoncoen** [comment]
It works! Thank you 🙌

**Comment by sters** [comment]
I can see the image. Thank you!
https://github.com/cloudspannerecosystem/wrench/pkgs/container/wrench
