### ISSUE TITLE
make wrench respect SPANNER_EMULATOR_HOST

### ISSUE THREAD

**Issue by 110y** [cloudspannerecosystem/wrench#14]
## WHAT

- make wrench respect SPANNER_EMULATOR_HOST

## WHY

- to use wrench for the emulator as well.

**Comment by blakevanlan** [comment]
Any idea why this doesn't work already? The Spanner client libraries should respect the `SPANNER_EMULATOR_HOST` env variable.

**Comment by 110y** [comment]
@blakevanlan 

Sorry for late response 🙏 
Now we can use `SPANNER_EMULATOR_HOST` with new version of `wrench` 1.0.3.
