### ISSUE TITLE
could not download Bazel

### ISSUE THREAD

**Issue by plemanach** [cloudspannerecosystem/wrench#53]
## Expected Behavior
make build should run ok

## Current Behavior

make build
bin/bazelisk build //:wrench
2022/04/27 18:44:31 could not download Bazel: could not determine filename to use for Bazel binary: unsupported machine architecture "arm64", must be x86_64
make: *** [build] Error 1

## Steps to Reproduce

1. make build

## Context (Environment)

Use a MacBook Pro M1

* wrench version: master

I cannot build wrench, probably bin/bazelisk need to be updated as well as the bazel version.

**Comment by 110y** [comment]
Sorry for the late, but this was resolved by previous update.
