### ISSUE TITLE
No binary release for v1.1.0 and embedded version is still 1.0.4

### ISSUE THREAD

**Issue by darklore** [cloudspannerecosystem/wrench#57]
Hello.

- There is no binary attached to release page. And also no 1.1.0 image is published to docker hub.
- Version number in https://github.com/cloudspannerecosystem/wrench/blob/v1.1.0/BUILD.bazel#L1 is still 1.0.4.

**Comment by hhanda** [comment]
Checking, if this is going to be resolved soon, have been waiting on this since the new version was released.

**Comment by 110y** [comment]
Sorry, I will attach a binary to the release soon 🙏

**Comment by 110y** [comment]
I just published binaries 🙏 

(I will automate this process....)

**Comment by darklore** [comment]
Thank you for quick response.
But docker image doesn't released to https://hub.docker.com/r/mercari/wrench/tags .
Did it become unsupported?
