### ISSUE TITLE
wrench 1.1.0 fails to parse `TIMESTAMP_SUB`

### ISSUE THREAD

**Issue by youxkei** [cloudspannerecosystem/wrench#61]
## Expected Behavior
wrench can apply DML including `TIMESTAMP_SUB` function.

## Current Behavior
It seems that wrench 1.1.0 fails to parse DML including `TIMESTAMP_SUB`.
wrench 1.0.4 can apply such DML correctly.

## Steps to Reproduce
The following reproduction steps assumes bash or zsh.

```sh
# $PROJECT, $INSTANCE, $DATABASE should be set properly

# setup
$ wrench apply --project $PROJECT --instance $INSTANCE --database $DATABASE --ddl <(echo "CREATE TABLE ParsingTimestampSub (CreatedAt TIMESTAMP NOT NULL) PRIMARY KEY (CreatedAt);")

# OK case
$ wrench apply --project $PROJECT --instance $INSTANCE --database $DATABASE --dml <(echo "DELETE FROM ParsingTimestampSub WHERE CreatedAt < CURRENT_TIMESTAMP();")
0 rows affected.

# error case
$ wrench apply --project $PROJECT --instance $INSTANCE --database $DATABASE --dml <(echo "DELETE FROM ParsingTimestampSub WHERE CreatedAt < TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 31 DAY);")
Error command: apply, version: unknown
        /proc/self/fd/11:1.94: got "31", want ")" or ","

# cleanup
$ wrench apply --project $PROJECT --instance $INSTANCE --database $DATABASE --ddl <(echo "DROP TABLE ParsingTimestampSub;")
```

## Context (Environment)

* wrench version: 1.1.0

**Comment by 110y** [comment]
Ah, it might be due to we migrated the query parser for `wrench` from regex to `spansql`...
Let me take a deeper look 👀

**Comment by zchee** [comment]
I'll also dig it.

**Comment by dtest** [comment]
I was having the same thing with `TIMESTAMP_ADD`. Looks like [spanner 1.40.0](https://github.com/googleapis/google-cloud-go/releases/tag/spanner%2Fv1.40.0) might fix this.

**Comment by 110y** [comment]
@dtest Thank you for letting me know that! Let me try to fix this 🙏

**Comment by kazegusuri** [comment]
If you still have a problem, please reopen.
